### ISSUE TITLE
Proxsuite import fails, name 'instructionset' is not defined

### ISSUE THREAD

**Issue by JonathanKuelz** [Simple-Robotics/proxsuite#119]
Hello dear proxsuite developers,

I am using a package with proxsuite as a dependency, but since yesterday, I cannot use it anymore as importing proxsuite fails.

**Reproduce**:
1. Create a new docker image based on the follwing dockerfile and `docker build -t proxsuite_debug .`:
```
FROM python:3.10
RUN pip install --no-cache-dir proxsuite
CMD [ "python" ]
```

2. Start a container (`docker run -it --rm proxsuite_debug`)
3. run `import proxsuite`

**Error**:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/cmeel.prefix/lib/python3.10/site-packages/proxsuite/__init__.py", line 36, in <module>
    load_main_module(globals=globals())
  File "/usr/local/lib/python3.10/site-packages/cmeel.prefix/lib/python3.10/site-packages/proxsuite/__init__.py", line 25, in load_main_module
    ("proxsuite_pywrap_avx512", instructionset.has_AVX512F),
NameError: name 'instructionset' is not defined
```

**Reason**:
According to the [platform docs](https://docs.python.org/3/library/platform.html), an empty string is a likely/frequent return for `platform.processor()`. However, looking at [the init script](https://github.com/Simple-Robotics/proxsuite/blob/main/bindings/python/proxsuite/__init__.py), it is bound to fail if it does because instructionset is not imported.

**Comment by fabinsch** [comment]
Hello @JonathanKuelz , thanks for raising this issue. You are right, the call to `platformplatform.processor()` returns `''`. We will change it and release a new version today. Sorry for the inconvenience.

**Comment by JonathanKuelz** [comment]
Great, thanks a lot for the quick support!

**Comment by jcarpent** [comment]
Thanks @JonathanKuelz for raising the issue and thanks to @fabinsch for the quick fix.
