### ISSUE TITLE
[cmake] Inverse PROXSUITE_DONT_VECTORIZE

### ISSUE THREAD

**Issue by ahoarau** [Simple-Robotics/proxsuite#13]
Hello all,

This is a proposal to modify `PROXSUITE_DONT_VECTORIZE` to `PROXSUITE_VECTORIZE` or `PROXSUITE_SMID`
As the library is header-only, it is simpler for people to simply copy and paste the library in their code.

Having this macro declared forces people to have this flag passed into their project.

Moreover, smide being an optional library library, it is better to enable the feature for that use case.

To be clear:

Use case 1 - simple copy --> No external dependencies, no flags necessary, easily portable library.
Use case 2 - building the lib for advanced users  with smide --> External dep, flags necessary, better use the prosuiteConfig etc.

What do you think ?

**Comment by jcarpent** [comment]
Good idea. But we are trying to follow Eigen way. What is your need?

**Comment by jcarpent** [comment]
In your current setup, you should use the target proxsuite-not-vectoriezed

**Comment by jcarpent** [comment]
Thanks for your helpful feedback

**Comment by ahoarau** [comment]
> Good idea. But we are trying to follow Eigen way. What is your need?

The need is trying to have the library in the most "portable" / "easy to test" way. 

Header-only libraries are great for that. Simply copy the headers in your project and you're good to go ! Many libs work that way (eigen, fmt, json, spdlog etc).

The thing with having compile_definitions needed for this simple case is that you have to read the CMake or "build" the library (mostly generate the cmake files) in order to get the right compilation flags. 

So in order to make things easy for the simple case, let's reverse the flags necessary when all extra features are disabled (matio, smid, etc).
