### ISSUE TITLE
[cmake] Hardcoded path in install space

### ISSUE THREAD

**Issue by ahoarau** [Simple-Robotics/proxsuite#14]
Hello Again,

The cmake config and targets contains some hardcoded-machine-dependant paths, making portability difficult.

![image](https://user-images.githubusercontent.com/703240/185102612-108cebaf-d1f2-4bc5-93ac-e6a6abdfc90a.png)

NOTE: To my biggest surprise, the pkgconfig is generic. it's usually the other way around

**Comment by jcarpent** [comment]
We will fix it next week. Where do you expect to point to?

**Comment by jcarpent** [comment]
@nim65s any idea of such hard coded path?

**Comment by jcarpent** [comment]
@ahoarau where did you install your lib?

**Comment by ahoarau** [comment]
> @ahoarau where did you install your lib?

Just in the build dir, could be anywhere. 

> We will fix it next week. Where do you expect to point to?

It should have some `${_IMPORT_PREFIX}` somewhere. Cmake has a few helpers to autogenerate everything. @traversaro ?

**Comment by traversaro** [comment]
> It should have some `${_IMPORT_PREFIX}` somewhere. Cmake has a few helpers to autogenerate everything. @traversaro ?
 
I am currently away from keyboard, I will be able to check this next week, if still necessary.

**Comment by jcarpent** [comment]
Are you on the devel branch? I think the main issue is in the way we build the header only target for cmake <= 3.19

**Comment by ahoarau** [comment]
I'm on master, windows (msvc 2022). cmake 3.24.0. Should I use another banch ?

**Comment by jcarpent** [comment]
Devel branch has some recent fixes

**Comment by ahoarau** [comment]
> cmeel has a check for this, so after 6fa8d903772bd5bbd19b47d476c92fd9b0fff8b5 this shouldn't happen.
> 
> @ahoarau : is your submodule also up-to-date ?

Yes everything is up to date. The script above is replacing a variable but shouldn't

**Comment by jcarpent** [comment]
See #17 for the fix

**Comment by ahoarau** [comment]
@jcarpent Seems like the problem is solved !

![image](https://user-images.githubusercontent.com/703240/186351957-44b05b34-d5a2-46e3-af64-24599d2ce893.png)

![image](https://user-images.githubusercontent.com/703240/186351997-52f61874-74cd-4f71-9e66-82bf38567d83.png)
