### ISSUE TITLE
Cannot build on Windows MSVC 2022 without vectorization support

### ISSUE THREAD

**Issue by ahoarau** [Simple-Robotics/proxsuite#15]
![image](https://user-images.githubusercontent.com/703240/185116723-cc1275ac-a817-4750-b92b-94ace89adffe.png)

Steps to reproduce:
Windows 10, msvc 2022, cmake 3.24.0, eigen 3.40.0

```cmake
git clone https://github.com/Simple-Robotics/proxsuite --recursive
cd proxsuite
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$(pwd)/install" -G Ninja -DINSTALL_DOCUMENTATION=OFF -DBUILD_WITH_VECTORIZATION_SUPPORT=OFF -DCMAKE_CXX_STANDARD=20 -DBUILD_TESTING=OFF
cmake --build build --config Release --target install
```

The cmake output:

![image](https://user-images.githubusercontent.com/703240/185117526-c1f9277b-aa5e-410a-ae22-e87af65380ea.png)

**Comment by jcarpent** [comment]
There is no error. This is just warnings.

**Comment by ahoarau** [comment]
I'm unfortunately constraint to use msvc. Any flags that would be added to silence those errors ?

**Comment by jcarpent** [comment]
With MSVC you can use clang-cl instead of vs143 for instance. We have in mind the compatibility with other MSVC compilers but we have limited ressources for that and other main priorities.

**Comment by jcarpent** [comment]
@ahoarau Could you manage to solve the issue with clang-cl?

**Comment by ahoarau** [comment]
> @ahoarau Could you manage to solve the issue with clang-cl?

We are stuck with msvc unfortunately

**Comment by jcarpent** [comment]
But you can change the compiler used behind. This is what we are doing on the CI for instance. Have you tried that solution?

**Comment by ahoarau** [comment]
Sorry for the misunderstanding. I meant "we are stuck with vs143".

**Comment by jcarpent** [comment]
Sorry then, we won't be able to help you with that. Mainly because I don't understand why you have to rely on vs143, which seems very limiting IMHO.
I will close this issue as it seems not related to ProxSuite, but rather to your personal usage.
We can continue the discussion if needed on a private channel.

**Comment by ahoarau** [comment]
This is the default windows compiler. Many users will need this support.

**Comment by ahoarau** [comment]
That would work meanwhile.

> Mainly because I don't understand why you have to rely on vs143, which seems very limiting IMHO.

Large codebase are not so simple to port. Compilers, c++ versions, os versions... Not too easy to do, especially for one lib
