### ISSUE TITLE
Regression on LISWET3 problem?

### ISSUE THREAD

**Issue by stephane-caron** [Simple-Robotics/proxsuite#160]
I can post a more detailed report, but just an early warning that the LISWET3 from Maros-Meszaros used to perform as follows on my machine with ProxQP 0.2.7:

- Default settings: solved in 146 seconds
- With ``eps_abs=1e-3``: solved in 3.16 seconds
- With ``eps_abs=1e-9``: not solved (at least not in <= 1000 seconds)

However it does not solve with default settings with ProxQP 0.3.0 (at least not in <= 1000 seconds).

**Comparison caveat:** I was running `proxsuite==0.2.7` from PyPI while now I'm running ``proxsuite=0.3.0` from conda.

### Extra context

Tabular details on ProxQP 0.2.7 performance:

| problem | solver | settings | runtime | found | primal_residual | dual_residual | duality_gap | cost_error |
|--|--|--|--|--|--|--|--|--|
| LISWET3 | proxqp | default | 145.59669646402472 | True | 8.24151833156428e-06 | 9.650276648620616e-08 | 0.0003489140499368 | 0.0008056529543516 |
| LISWET3 | proxqp | high_accuracy | 0.0 | False | inf | inf | inf |  |
| LISWET3 | proxqp | low_accuracy | 3.162652347004041 | True | 0.0008081155198323 | 1.0899415509024736e-08 | 0.0419660059992565 | 0.0448540420093301 |

**Comment by jcarpent** [comment]
I think we have added the check for the duality gap ...

**Comment by stephane-caron** [comment]
Confirmed in https://github.com/stephane-caron/qpsolvers_benchmark/commit/ecfaa2760ce134366317d7110cbd8d744456ef26 that this problem is now solved.
