### ISSUE TITLE
Ship dependencies with FetchContent or CPM

### ISSUE THREAD

**Issue by ahoarau** [Simple-Robotics/proxsuite#176]
Hello Again,

As a user, it would save me a lot a time if the dependencies could be added automatically, to avoid having to install them manually.
It would make the repo self-contained.

### Proposed Solution

Use [`FetchContent`](https://cmake.org/cmake/help/latest/module/FetchContent.html) (or [CPM](https://github.com/cpm-cmake/CPM.cmake)) to handle external dependencies.

It would look like this:
```cmake
include(FetchContent)

# cmake modules
FetchContent_Declare(
cmake_modules
GIT_URL https://github.com/jrl-umi3218/jrl-cmakemodules.git
GIT_TAG 9403226002b930d592ca83b50d3cd714a1c2dc01
SOURCE_DIR cmake_modules
)
FetchContent_MakeAvailable(cmake_modules)

# eigen
FetchContent_Declare(
  Eigen
  GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git
  GIT_TAG 3.4.0
  GIT_SHALLOW TRUE
  GIT_PROGRESS TRUE)
set(EIGEN_BUILD_DOC OFF)
set(EIGEN_BUILD_TESTING OFF)
set(EIGEN_BUILD_PKGCONFIG OFF)
FetchContent_MakeAvailable(Eigen)

target_link_libraries(proxsuite PRIVATE Eigen3::Eigen)

```

Same for `smide` etc. 
Good things:
* You can still use `find_package()`, either by using `QUIET` and `_FOUND` or  via the new `FETCHCONTENT_TRY_FIND_PACKAGE_MODE` cmake 3.24 https://cmake.org/cmake/help/latest/module/FetchContent.html#variable:FETCHCONTENT_TRY_FIND_PACKAGE_MODE

* No mode submodules (<<< no more "I forgot to clone with --recursive ....")

What do you think ?

**Comment by jcarpent** [comment]
On our side, we are trying to use the system or local dependencies by default to have a uniform process for all the libraries with common dependencies.
If you want, we can add an option to fetch them directly if strictly mentioned.
Could you handle this feature adding?

Thanks in advanced for your help!
Justin

**Comment by ahoarau** [comment]
You can still have the standard behavior with the QUIET+_FOUND or `FETCHCONTENT_TRY_FIND_PACKAGE_MODE` option.
It will try to use `find_package()` first, and go for fetchcontent otherwise. Pretty neat.
Are you ok with having cmake 3.24 a minimum version ?

**Comment by jcarpent** [comment]
The thing is that we need to support 18.04 for some specific robots. So the short answer is that we cannot force to 3.24 unfortunately.

**Comment by jcarpent** [comment]
@ahoarau Any update on this action?

**Comment by jcarpent** [comment]
I will close this issue as there is no more activity. Feel free to investigate it @ahoarau when you have time
