### ISSUE TITLE
Enable pip installation on Windows

### ISSUE THREAD

**Issue by ottapav** [Simple-Robotics/proxsuite#179]
Please make possible to use 'pip install proxsuite' on Windows.

**Comment by jcarpent** [comment]
In the meantime you can rely on conda for using ProxSuite on Windows

**Comment by jcarpent** [comment]
@nim65s Do you know what is missing to use your tools to deploy on pip package with Windows support?

**Comment by nim65s** [comment]
It should already be working with WSL, and was tested in a few cases, but not proxsuite yet I think.
For a more general  windows support, I would need someone with a better understanding of windows and/or a lot of time.

**Comment by fabinsch** [comment]
Hello @ottapav, with the latest release of `proxsuite-0.3.4` it is now possible to run `pip install proxsuite` on windows.

**Comment by ottapav** [comment]
@fabinsch Thank you for the effort! I'm new in Python, so I maybe missing something, yet, when I install the proxsuite (using the `pip install proxsuite`) in my virtual environment, I'm missing proxsuite folder with the files (only the wheel info is there):
![image](https://user-images.githubusercontent.com/10757098/222411369-bc743b40-ecd8-444d-99c9-6697c7dfcad3.png)

Are there some other steps that need to be done to be able to run your scripts?

**Comment by fabinsch** [comment]
Hi, the files can be found under `\YOUR_ENV\\lib\\site-packages\\cmeel.prefix\\lib\\python3.XX\\site-packages\\proxsuite\\` and  `\YOUR_ENV\\lib\\site-packages\\cmeel.prefix\\include\\proxsuite\\`.

To get this for your case, just do from bash
```
python
import proxsuite
proxsuite.__file__
```
