### ISSUE TITLE
updating LDL cholesky decomposition

### ISSUE THREAD

**Issue by pengfzhou** [Simple-Robotics/proxsuite#192]
I have one question that when penalization parameter $\mu_e$ changed, how to update LDL cholesky decomposition.  It seems that when penalization parameter $\mu_e$ changed, the problem is how to update  LDL cholesky decomposition with respect to adding an diagonal matrix with size of number of equality constrains., which should be  different from updating LDL cholesky decomposition with rows and colmns added.

**Comment by Bambade** [comment]
Hi @pengfzhou. It is indeed different. The **Updating the decomposition** part of this [wikipedia article](https://en.wikipedia.org/wiki/Cholesky_decomposition) article provides first good insights of how updating the factorization (for both Cholesky and LDLT decompositions), will it be for updating a row or column (using for e.g., rank one updates) or adding or removing columns or rows. Their exists then different strategies for doing it efficiently by taking advantage of the structure of the matrix (in the sparse case for example, you can have a look if you are interested by Tim Davis literature on the subject).

**Comment by pengfzhou** [comment]
Thanks for your reply~  I have already  study the  paper "ROW MODIFICATIONS OF A SPARSE CHOLESKY
FACTORIZATION", when  I come into other scene like QP active set.   I am curious about how to update the factorization when add a diagonal marix, which should correspond to change of penalization parameter $\mu_e$ from my point, can you provide any simple insight? Or if penalization paremater $\mu_e$ changed, we just refactorize?

**Comment by Bambade** [comment]
Refactorizing the full matrix would be too costly. It is better to apply rank updates (e.g., several rank one updates) for updating the penalizing parameter $\mu_e$ (the wikipedia article provides more details on it ; in practice it would then correspond to refactorizing only the part of the original matrix with the new penalization parameter). 
The sparse case is studied also in section 4.2 of  "ROW MODIFICATIONS OF A SPARSE CHOLESKY
FACTORIZATION" for the LDLT (it corresponds to the case when you update an unique element of the row matrix).
