### ISSUE TITLE
Error: pip install seems not to work,

### ISSUE THREAD

**Issue by pengfzhou** [Simple-Robotics/proxsuite#195]
(base) z00617747@huawei:~/software$ pip install proxsuite-0.3.4-0-cp38-cp38-manylinux_2_35_x86_64.whl 
ERROR: proxsuite-0.3.4-0-cp38-cp38-manylinux_2_35_x86_64.whl is not a supported wheel on this platform.
(base) z00617747@huawei:~/software$ pip --version
pip 21.0.1 from /home/z00617747/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
my platform is Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-197-generic x86_64)

**Comment by jcarpent** [comment]
In the meantime you can install it with conda. Could you please report the log error?

**Comment by jcarpent** [comment]
Duplicate with #194
