### ISSUE TITLE
Linearly dependent constraints

### ISSUE THREAD

**Issue by pianist1234567i** [Simple-Robotics/proxsuite#199]
Thanks, guys. This solver is much faster than any others in my project. However, when I do a test of adding many linearly dependent constraints, the speed of solver will be slown down. Would you mind giving any advice to handle this?

**Comment by jcarpent** [comment]
Thanks for your interest in ProxSuite 
Could you please share a problem example? It will help us to answer your questions

**Comment by jcarpent** [comment]
I will close this issue as there is no feedback from @pianist1234567i
