### ISSUE TITLE
Julia bindings?

### ISSUE THREAD

**Issue by dfridovi** [Simple-Robotics/proxsuite#2]
Hi there - not sure if you remember me, but we talked at your poster at RSS yesterday. I'm a relatively recent C++ => Julia convert, and I would *love* to use your solver in Julia. Thanks so much for the great work, and keep it up!

**Comment by jcarpent** [comment]
This is now available by installing ProxSuite Python bindings and using PyCall. See https://github.com/Simple-Robotics/proxsuite/blob/e97f76605da03ae624927b3615cb2540144bbacc/examples/julia/overview-simple.jl for further examples.

**Comment by dfridovi** [comment]
Thanks!
