### ISSUE TITLE
Add a wheel for Apple M1 and Python 3.11

### ISSUE THREAD

**Issue by MB-29** [Simple-Robotics/proxsuite#256]
Hi !

I just wanted to let know that `pip install` doesn't find a wheel on my Macbook Pro M1 (AArch64) on Python 3.11 

> No matching distribution found for proxsuite

Though `brew install` worked well 👍

**Comment by jcarpent** [comment]
You can use conda if you want for Python and C++ install.
We are working on the full support of modern Apple arch.

**Comment by jcarpent** [comment]
The issue has been solved by @fabinsch. Thanks to him for the very quick fix ;)
