### ISSUE TITLE
Include failure: couldn't find "proxsuite/config.hpp"

### ISSUE THREAD

**Issue by jiayy21** [Simple-Robotics/proxsuite#267]
Hello!
I tried to include Proxsuite as an external package and use it in a C++ project. The building of Proxsuite was successful, but I encountered an error when trying to include proxsuite/proxqp/dense/dense.hpp.
```
/build/external/src/proxsuite/include/proxsuite/helpers/common.hpp:11:10: fatal error: proxsuite/config.hpp: no such file or directory
11 | #include "proxsuite/config.hpp"
```
I indeed couldn't find this file  "proxsuite/config.hpp". 

What should I do about it, please

**Comment by fabinsch** [comment]
Hi @jiayy21,

the `config.hpp` is automatically generated by the submodule `cmake-module` that comes with proxsuite. Usually, this is nothing you have to take care of. After building proxsuite, you will see this file appearing in your build folder: `/build/include/proxsuite/`

Did you try to set up your project using cmake as described in the [readme](https://github.com/Simple-Robotics/proxsuite#using-proxsuite-with-cmake)?
