### ISSUE TITLE
Question about installation from source.

### ISSUE THREAD

**Issue by ProphecyQAQ** [Simple-Robotics/proxsuite#270]
Hello!
I saw paper about  qplayer [https://inria.hal.science/hal-04133055/document](url) and want to use it. I found it seems to be implemented in [https://github.com/Bambade/proxsuite](url) on qplayer branch but still not merged.  
So I tried to install from source code following procedure Build the Python interface. But it not install successfully, it show No module named 'proxsuite'. And my python environmet based on anaconda3. Could you give me some help?

Thanks and Please forgive me for my poor English.

**Comment by fabinsch** [comment]
Hi @ProphecyQAQ,

thanks for your interest in our work on QPLayer and its implementation. We are (almost) done with the PR and facing some minor ci issues on windows. On Mac and Linux, everything is working well.

You can follow the following steps
```
conda create -n qplayer python=3.9
conda activate qplayer

# install proxsuite dependencies
conda install proxsuite --only-deps
# install pytorch which is needed for qplayer
conda install pytorch torchvision torchaudio cpuonly -c pytorch

# clone the repo, fetch the PR and check it out
git clone --recursive git@github.com:Simple-Robotics/proxsuite.git 
cd proxsuite
git fetch origin pull/264/head:qplayer
git co qplayer

# build it with openmp support
conda install cmake
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_INTERFACE=ON -DBUILD_TESTING=OFF -DBUILD_WITH_OPENMP_SUPPORT=ON
make install -j8

# test import
python -c "from proxsuite.torch.qplayer import QPFunction"

# run example script, you need cvxpy for the creating of the task
conda install cvxpy 
python <proxsuite_src_dir>/examples/python/qplayer_sudoku.py
```

I hope this helps to build QPLayer.

**Comment by ProphecyQAQ** [comment]
When I run `cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_INTERFACE=ON -DBUILD_TESTING=OFF -DBUILD_WITH_OPENMP_SUPPORT=ON`, it raised 

 CMake Error: The source directory "OpenMPTryFlag.cpp" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
CMake Error at cmake-module/find-external/OpenMP/FindOpenMP.cmake:222 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  cmake-module/find-external/OpenMP/FindOpenMP.cmake:549 (_openmp_get_flags)
  CMakeLists.txt:84 (find_package)

My ubuntu version is 18.04 and openMP version is _OPENMP 201511.

**Comment by jcarpent** [comment]
Ubuntu 18.04 is no longer supported. I would suggest updating your OS version ;-)

**Comment by ProphecyQAQ** [comment]
> Ubuntu 18.04 is no longer supported. I would suggest updating your OS version ;-)

You're right, 18.04 is a little older.  
I set `-DBUILD_WITH_OPENMP_SUPPORT=OFF` it built successfuly and can run well.  Thanks for your kindly help.
