### ISSUE TITLE
Too strict symmetric check in model.is_valid()

### ISSUE THREAD

**Issue by whtqh** [Simple-Robotics/proxsuite#271]
I met some check error with this line, even though my H is a symmetric matrix in double precision.

https://github.com/Simple-Robotics/proxsuite/blob/7f4b78773bebd82f64d2baf38db469554759336b/include/proxsuite/proxqp/dense/model.hpp#L123C58-L123C58

I suggest to replace 0 with std::numeric_limits<T>::epsilon()

**Comment by fabinsch** [comment]
hi @whtqh, thanks for the hint. Can you check if the changes in #272 solve your issue?

**Comment by fabinsch** [comment]
Hey @whtqh,

I am happy to see that this solved your problem. Could you please provide us the data of the QP, or your H matrix that failed before and works now? Then we could add this as a unittest in our repo.

Thanks for your help,
Fabian
