### ISSUE TITLE
Order of arguments in c++ api

### ISSUE THREAD

**Issue by aescande** [Simple-Robotics/proxsuite#34]
So far, the order of arguments to describe the inequality constraints `l <= C x <= u` is `C, u, l` which is not very intuitive and different fron the common `C, l, u`.
If it is still time to fix the order, it would avoid surprises for the user.

**Comment by jcarpent** [comment]
I totally agree with this remark. 
@Bambade Could you handle it?

**Comment by Bambade** [comment]
Yes, thanks for the remark!

**Comment by jcarpent** [comment]
Solved via #39.
