### ISSUE TITLE
Move from pybind11 to nanobind

### ISSUE THREAD

**Issue by ManifoldFR** [Simple-Robotics/proxsuite#340]
After discussing with @jorisv, we think that upgrading from pybind11 to [nanobind](https://github.com/wjakob/nanobind) for proxsuite would be beneficial and an opportunity to cut our teeth on this newer bindings library, see what works, what doesn't, and what's easier to do now.

**Comment by jcarpent** [comment]
Looks perfect to me. Thanks @ManifoldFR for this suggestion.

**Comment by ManifoldFR** [comment]
Took the afternoon working on this. The bindings compile atm, still have something to do with respect to the CMake install step.

**Comment by stephane-caron** [comment]
Nice initiative! When it is ready we could run the [qpbenchmark](https://github.com/qpsolvers/qpbenchmark) test sets [1](https://github.com/qpsolvers/free_for_all_qpbenchmark), [2](https://github.com/qpsolvers/mpc_qpbenchmark), [3](https://github.com/qpsolvers/maros_meszaros_qpbenchmark) to do a pybind11/nanobind comparison of computation times.

**Comment by jcarpent** [comment]
Solve via #345.
