### ISSUE TITLE
Query: compute_timings unit

### ISSUE THREAD

**Issue by youssef-aboudorra** [Simple-Robotics/proxsuite#341]
Hello,

Thanks for developing proxsuite.

I have a question regarding the unit of compute_timings: sol_time, setup_time, run_time.

What is the unit of the timing info? is it microseconds?
I failed to find it in the documentation.

Best Regards,
Youssef

**Comment by fabinsch** [comment]
Hi @youssef-aboudorra,

thanks for your interest in ProxSuite. Yes, you are right. The computed timings are in microseconds.
I just verified it in our timer [here](https://github.com/Simple-Robotics/proxsuite/blob/main/include/proxsuite/proxqp/timings.hpp#L52) (l.51-55 and l.76-80), which is used when you print the timings from `results.info.solve_time` etc.

We will state this more clearly in our docs.

Cheers,
Fabian

**Comment by youssef-aboudorra** [comment]
Hi @fabinsch 

Great.
Thanks a lot for the prompt reply!

Regards,
Youssef
