### ISSUE TITLE
AttributeError when using python module VectorQP

### ISSUE THREAD

**Issue by wanghf15** [Simple-Robotics/proxsuite#344]
python 3.8.10
proxsuite-0.6.6 was installed

>>> import proxsuite
>>> proxsuite.proxqp.dense.VectorQP()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'proxsuite.proxsuite_pywrap_avx2.proxqp.dense' has no attribute 'VectorQP'

**Comment by fabinsch** [comment]
you just get `VectorQP` if proxsuite is build with openmp support.
