### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by stephane-caron** [Simple-Robotics/proxsuite#5]
There is a broken link in the README, pointing to a repository from @Bambade that is likely not set to Public yet:

> The numerical benchmarks of ProxQP against other commercial and open-source solvers are available [here](https://github.com/Bambade/qp_benchmark).

Can't wait to try out ProxQP!

**Comment by jcarpent** [comment]
@Bambade could open access to the repository ?

**Comment by Bambade** [comment]
I have created a new repo with the benchmarks in Simple-Robotics: https://github.com/Simple-Robotics/proxqp_benchmark, as suggested by @jcarpent.
