### ISSUE TITLE
Reimplement AMD under BSD-3

### ISSUE THREAD

**Issue by Brian-Acosta** [Simple-Robotics/proxsuite#77]
We are interested in adding ProxQP support to [dairlib](https://github.com/DAIRLab/dairlib) as a solver for MPC and whole-body control problems, and eventually to [Drake](https://github.com/RobotLocomotion/drake) as a supported solver. This requires being able to build against Eigen with the EIGEN_MPL2_ONLY flag enabled to comply with Drake's strict licensing rules. 

I see from [this](https://github.com/Simple-Robotics/proxsuite/blob/c32bb2f0114364f0ed22aa36e83a325177c7a3da/include/proxsuite/linalg/sparse/factorize.hpp#L729) comment that there are plans to make this happen. 

I can continue with that build flag disabled for now, as I am highly unlikely to have the bandwidth to implement such a change anytime soon myself. I just wanted to let you know that the change would be greatly appreciated!

Thanks for the great software!

**Comment by jcarpent** [comment]
Thanks @Brian-Acosta for your interest in ProxSuite.
We have a plan to use the LDL factorization of OSQP which seems to comply with all the rules for BSD, which should also provide also the AMD sorting.
This will require some internal change within our framework.

We would be very happy to have ProxSuite integrated into Drake in general.
Thanks a lot @Brian-Acosta for handling this task when we are done with the sparse back end.

**Comment by fabinsch** [comment]
Hello @Brian-Acosta, I am not sure whether to understand 100% your problem with the AMD ordering. You are saying 
> This requires being able to build against Eigen with the EIGEN_MPL2_ONLY flag enabled

but when I check the [Eigen headers](https://eigen.tuxfamily.org/dox/Ordering_8h_source.html) of `AMDOrdering` and in general the Eigen [license FAQ](http://eigen.tuxfamily.org/index.php?title=Licensing_FAQ), it seems to me that the ordering should be MPL2 compliant.

Maybe I am missing something here, I would be happy if you could explain me further your issue.

**Comment by Brian-Acosta** [comment]
Hi Fabian, looks like this is only an [Eigen 3.3](https://eigen.tuxfamily.org/dox-3.3/Ordering_8h_source.html) issue. Drake is migrating to Eigen 3.4 soon, so it should be a non-issue then. Thanks for looking into it.

**Comment by Brian-Acosta** [comment]
We do not currently have a timeline. After my initial prototype (in the DAIRLab repo [here](https://github.com/DAIRLab/dairlib/blob/proxsuite/solvers/fast_proxqp_solver.cc)), I found ProxQP was about as fast as OSQP (although this is without vectorization) for our Cassie standing controller, and it was unstable when used for our walking controller. I am not an optimization expert but perhaps you all have some ideas for why this is. 

Both controllers are using the same [operational space control](https://github.com/DAIRLab/dairlib/blob/da517eb058300cf85c3baeeb7db656dca098cb4a/systems/controllers/osc/operational_space_control.h#L35) framework,

I find that I needed to ask for much higher accuracy than with OSQP to achieve good results with the standing controller, so perhaps the conditioning of our problem is challenging. I would be happy to log some QPs and provide them for benchmarking.  

If we can show that it improves our Cassie OSC and provide a working interface, that would make a compelling case to the Drake team to take on supporting ProxQP.

**Comment by jcarpent** [comment]
We would be pleased to provide you with some guidance on solving your issues. 
For the best performances with ProxQP, you will need vectorization support.
In your code, you are using the sparse solver. I would instead recommend you use the dense one, which is much more suited for robotics, and we have been integrating so far in [TSID](https://github.com/stack-of-tasks/tsid/)

Could you extract the problem matrices for the hard problem you're encountering? 
We will soon provide a simple way of serializing qp data ;)
