### ISSUE TITLE
Regression on QFORPLAN problem?

### ISSUE THREAD

**Issue by stephane-caron** [Simple-Robotics/proxsuite#80]
ProxQP 0.2.2 used to solve the QFORPLAN problem with the following timings on my machine (reproduction code below):

```console
$ pip install proxsuite==0.2.2
Defaulting to user installation because normal site-packages is not writeable
...
Successfully installed proxsuite-0.2.2
$ python reprod.py
Solving dense...
Time: 24.1527040459996 s
Solving sparse...
Time: 5.297871345999738 s
```

Now with ProxQP 0.2.4 it does not terminate after at least 7 min:

```console
$ pip install proxsuite==0.2.4
Defaulting to user installation because normal site-packages is not writeable
...
Successfully installed proxsuite-0.2.4
$ python reprod.py
Solving dense...
```

### Reproduction

Decompress ``QFORPLAN.mat`` from [QFORPLAN.zip](https://github.com/Simple-Robotics/proxsuite/files/9926843/QFORPLAN.zip) then run:

```python
from time import perf_counter

import proxsuite
import scipy.io as spio
import scipy.sparse as spa

m = spio.loadmat("QFORPLAN.mat", squeeze_me=True)
P = m["P"].astype(float)
q = m["q"].astype(float)
A = m["A"].astype(float)
b = m["b"].astype(float)
C = m["C"].astype(float)
l = m["l"].astype(float)
u = m["u"].astype(float)
print("Solving dense...")
start = perf_counter()
proxsuite.proxqp.dense.solve(P, q, A, b, C, l, u)
print(f"Time: {perf_counter() - start} s")

P = spa.csc_matrix(P)
A = spa.csc_matrix(A)
C = spa.csc_matrix(C)
print("Solving sparse...")
start = perf_counter()
proxsuite.proxqp.sparse.solve(P, q, A, b, C, l, u)
print(f"Time: {perf_counter() - start} s")
```

**Comment by jcarpent** [comment]
Hi @stephane-caron,

Thanks for raising this issues.
The major change concerns the default value of `eps_abs` from `1e-3` to `1e-5` for default desired accuracy.
On my side, I have with 0.2.4 these values:
```
Solving dense...
Time: 4.864116859971546 s
Solving sparse...
Time: 3.3215316309942864 s
```

I guess your computer is pretty old, so I would suggest changing the default value:
`proxsuite.proxqp.dense.solve(P, q, A, b, C, l, u, eps_abs=1e-3)`

**Comment by stephane-caron** [comment]
>  The major change concerns the default value of eps_abs from 1e-3 to 1e-5 for default desired accuracy.

I confirm that passing `eps_abs=1e-3` to the dense backend in 0.2.4 does not result in a hang.

> I guess your computer is pretty old, so I would suggest changing the default value:

It is indeed an Intel(R) Core(TM) i7-6500U :older_adult: 

One thing is strange though: with 0.2.4, passing `verbose=True` to the dense backend (leaving out `eps_abs` to its default), the solver _does_ find a solution in 14 s:

```
-------------------SOLVER STATISTICS-------------------
outer iter:   30
total iter:   6615
mu updates:   9
rho updates:  1
objective:    7.46e+09
status:       Solved
run time:     1.42e+07
--------------------------------------------------------
```

However when passing `verbose=False` it hangs as reported :thinking: 

The two outcomes are repeatable.

**Comment by jcarpent** [comment]
I'm able to reproduce with the provided docker image. Thanks for this great effort.
@stephane-caron Could you try to use proxsuite from conda?

**Comment by jcarpent** [comment]
Another question, is it only related to this particular problem?
@stephane-caron Could you try with another problem?

**Comment by jcarpent** [comment]
Good news, Proxsuite 0.2.5 solved the issue.
Thanks @stephane-caron for the issue. We really need you ;)
