### ISSUE TITLE
CMake-Version requirement is wrong

### ISSUE THREAD

**Issue by fennel-labs** [Simple-Robotics/proxsuite#96]
The CMakeLists.txt set the minimum required version of CMake to 3.10.
However, the [FindSimde.cmake](https://github.com/jrl-umi3218/jrl-cmakemodules/blob/c1439c9894173c80e44173fd6af17232f20fa2dd/find-external/Simde/FindSimde.cmake) file requires a higher version of CMake as the option REASON_FAILURE_MESSAGE is only available in CMake 3.16 and higher (see [3.16](https://cmake.org/cmake/help/v3.16/module/FindPackageHandleStandardArgs.html) vs [3.15](https://cmake.org/cmake/help/v3.15/module/FindPackageHandleStandardArgs.html)). 
Furthermore, the error `target_compile_definitions may only be set INTERFACE properties on INTERFACE targets` is triggered when the former error is fixed by removing the unsupported option.

## Steps to reproduce

Try manual build with CMake 3.10.

## Suggestions

Either remove unsupported commands for CMake 3.10 or bump up CMake version in CMakeLists.txt.

**Comment by jcarpent** [comment]
Thanks @fennel-labs for raising this issue. We will work on it soon.
@fabinsch Could you handle it?

**Comment by jcarpent** [comment]
> Furthermore, the error `target_compile_definitions may only be set INTERFACE properties on INTERFACE targets` is triggered when the former error is fixed by removing the unsupported option.

@fennel-labs Could you provide the full log for this error?

**Comment by jcarpent** [comment]
Solved with #98

**Comment by fennel-labs** [comment]
@jcarpent @fabinsch I confirm, thank you very much!
